# Generated by Django 2.2 on 2019-09-24 18:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(max_length=2000)),
                ('optional_applicable_conditions', models.CharField(max_length=2000)),
                ('references', models.CharField(max_length=2000)),
            ],
            options={
                'ordering': ['recommendation'],
            },
        ),
        migrations.CreateModel(
            name='Patientrecommendations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Patient', verbose_name='Recommendations')),
            ],
        ),
        migrations.CreateModel(
            name='Patientguidelines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guideline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Patient', verbose_name='Recommendations')),
            ],
        ),
        migrations.CreateModel(
            name='Patientdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350)),
                ('date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(max_length=10)),
                ('systolic_BP', models.IntegerField()),
                ('diastolic_BP', models.IntegerField()),
                ('smoking_years', models.IntegerField()),
                ('no_of_packs', models.IntegerField()),
                ('fasting_blood_sugar', models.IntegerField()),
                ('hypothyroid', models.CharField(max_length=5)),
                ('obese', models.CharField(max_length=5)),
                ('intravenous_drug_abuse', models.CharField(max_length=5)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
